password: ubuntu
ssh_pwauth: true
chpasswd:
  expire: false
users:
  - default
  - name: ubuntu
    groups: [adm, dialout, cdrom, floppy, sudo, audio, dip, video, plugdev, netdev]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    plain_text_passwd: ubuntu
    lock_passwd: false
